In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

## if response code is 403

- headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} -requests.get('url',headers=headers).text

In [2]:
url = 'https://ambitionbox.com/list-of-companies?page=1'
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage = requests.get(url,headers=headers).text

In [3]:
soup=BeautifulSoup(webpage, 'lxml')

In [4]:
# print(soup.prettify())

In [5]:
soup.find_all('h1')[0].text

'\n\t\t\t\t\tTop Companies in\n\t\t\t\t \n\t\t\t\t\tINDIA\n\t\t\t\t\t'

## To Find out names of the companies

In [6]:
for i in soup.find_all('h2', class_='companyCardWrapper__companyName'):
    print(i.text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM

In [7]:
for i in soup.find_all('p'):
    print(i.text.strip())

AmbitionBox
About Company
Discover best places to work
Compare & find best workplace
Bring your workplace to life
Highlight your company's perks
Read reviews for 6L+ companies
Rate your former or current company
Discover salaries for 6L+ companies
Calculate your take home salary
Check your market value
Decode your offer letter
Help other jobseekers
Check your gratuity amount
Check how much of your HRA is tax-free
Check your salary hike
Read interviews for 40K+ companies
Contribute your interview questions
AmbitionBox Employee Choice Awards - 5th Edition
AmbitionBox Employee Choice Awards - 4th Edition
AmbitionBox Employee Choice Awards - 3rd Edition
Popular
AmbitionBox Award Winner'26
AmbitionBox Award Winner'26
AmbitionBox Award Winner'26
AmbitionBox Award Winner'26
Side-by-side comparison to make informed career
										decisions
Trusted by over
									1.5 Crore
									job seekers to find their right fit company
Reviews
Salaries
Interviews
Users
About Company
Made with ❤️ in India. Trademarks belong to their respective owners. All
					rights reserved © 2026 Info Edge (India) Ltd.

## To Find out the Ratings

In [ ]:
len(soup.find_all('div', class_='rating_text'))

20

## To Find out the number of reviews

In [9]:
len(soup.find_all('span', class_='companyCardWrapper__ActionCount'))

120

## Considering the whole container

In [10]:
company=soup.find_all('div', class_='companyCardWrapper')

In [11]:
len(company)

20

In [41]:
name=[]
rating=[]
reviews=[]
hq=[]
no_of_jobs=[]

for i in company:

    name.append(i.find('h2', class_='companyCardWrapper__companyName').text.strip())
    rating.append(i.find('div', class_='rating_text').text.strip())
    reviews.append(i.find('span', class_='companyCardWrapper__ActionCount').text.strip())
    hq.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip())
    no_of_jobs.append(i.find('span', class_='companyCardWrapper__ActionCount').text.strip())

df = pd.DataFrame({
    'name': name,
    'rating': rating,
    'reviews': reviews,
    'Head_Quarters': hq,
    'No_of_Jobs': no_of_jobs
})

In [13]:
name

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Jio',
 'Axis Bank',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTIMindtree',
 'IBM']

In [42]:
rating

['3.8',
 '4.2',
 '3.5',
 '3.9',
 '3.7',
 '3.9',
 '3.9',
 '4.0',
 '3.5',
 '3.5',
 '3.9',
 '3.5',
 '4.0',
 '3.9',
 '3.6',
 '4.1',
 '3.7',
 '4.0',
 '3.7',
 '3.9']

In [15]:
reviews

['1.1L',
 '73.1k',
 '64.8k',
 '61.1k',
 '53k',
 '52k',
 '48.5k',
 '45.8k',
 '45.7k',
 '43k',
 '42k',
 '38.2k',
 '33.5k',
 '33k',
 '32.1k',
 '31.3k',
 '27.2k',
 '26.9k',
 '26.3k',
 '25.7k']

In [16]:
hq

['IT Services & Consulting | Bengaluru +441 other locations',
 'IT Services & Consulting | Bengaluru +259 other locations',
 'IT Services & Consulting | Hyderabad +372 other locations',
 'IT Services & Consulting | Hyderabad +231 other locations',
 'IT Services & Consulting | Bengaluru +180 other locations',
 'Banking | Mumbai +1843 other locations',
 'IT Services & Consulting | Bengaluru +243 other locations',
 'IT Services & Consulting | Chennai +231 other locations',
 'Banking | Mumbai +1442 other locations',
 'IT Services & Consulting | Hyderabad +322 other locations',
 'Analytics & KPO | Hyderabad +181 other locations',
 'BPO | Mumbai +254 other locations',
 'Telecom | Mumbai +1956 other locations',
 'Banking | Mumbai +1516 other locations',
 'BPO | Bengaluru +181 other locations',
 'Internet | Bengaluru +515 other locations',
 'Retail | Mumbai +1157 other locations',
 'BPO | Noida +51 other locations',
 'IT Services & Consulting | Bengaluru +144 other locations',
 'IT Services & Consulting | Bengaluru +161 other locations']

In [17]:
no_of_jobs

['1.1L',
 '73.1k',
 '64.8k',
 '61.1k',
 '53k',
 '52k',
 '48.5k',
 '45.8k',
 '45.7k',
 '43k',
 '42k',
 '38.2k',
 '33.5k',
 '33k',
 '32.1k',
 '31.3k',
 '27.2k',
 '26.9k',
 '26.3k',
 '25.7k']

In [18]:
df.shape

(20, 5)

## Creating DataFrame for all the pages

In [45]:
# final=pd.DataFrame()
all_dfs = []

for j in range(1, 7):
    url = 'https://ambitionbox.com/list-of-companies?page={}'.format(j)
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
    webpage = requests.get(url,headers=headers).text
    soup=BeautifulSoup(webpage, 'lxml')
    company=soup.find_all('div', class_='companyCardWrapper')

    name, rating, reviews, hq, no_of_jobs = [], [], [], [], []

    for i in company:

        name.append(i.find('h2').text.strip() if i.find('h2') else np.nan)

        rating.append(i.find('div', class_='rating_text').text.strip()
                    if i.find('div', class_='rating_text') else np.nan)

        reviews.append(i.find('span', class_='companyCardWrapper__ActionCount').text.strip()
                    if i.find('span', class_='companyCardWrapper__ActionCount') else np.nan)

        hq.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip()
                if i.find('span', class_='companyCardWrapper__interLinking') else np.nan)

        no_of_jobs.append(i.find_all('span', class_='companyCardWrapper__ActionCount')[1].text.strip()
                        if len(i.find_all('span', class_='companyCardWrapper__ActionCount')) > 1 else np.nan)
            
    df = pd.DataFrame({
        'Name': name,
        'Rating': rating,
        'Reviews': reviews,
        'Head_Quarters': hq,
        'No_of_Jobs': no_of_jobs
    })

    print(f"Page {j}: {len(company)} companies")

    all_dfs.append(df)
            
final=pd.concat(all_dfs, ignore_index=True)

Page 1: 20 companies
Page 2: 20 companies
Page 3: 20 companies
Page 4: 20 companies
Page 5: 20 companies
Page 6: 20 companies

In [36]:
final.sample(5)

,name,rating,reviews,Head_Quarters,No_of_Jobs
9,Tech Mahindra,NaN,43k,IT Services & Consulting | Hyderabad +322 othe...,2.9L
84,Tata Projects,NaN,6.8k,Engineering & Construction | Mumbai +284 other...,22.6k
37,PwC,NaN,12.5k,Management Consulting | Bengaluru +135 other l...,1.2L
82,Megha Engineering & Infrastructures,NaN,6.9k,Engineering & Construction | Hyderabad +407 ot...,18.6k
49,Maruti Suzuki,NaN,9.5k,Automobile | Gurugram +455 other locations,28.3k

In [46]:
final

,Name,Rating,Reviews,Head_Quarters,No_of_Jobs
0,TCS,3.3,1.1L,IT Services & Consulting | Bengaluru +441 othe...,10.1L
1,Accenture,3.7,73.1k,IT Services & Consulting | Bengaluru +259 othe...,6.9L
2,Wipro,3.6,64.8k,IT Services & Consulting | Hyderabad +372 othe...,4.9L
3,Cognizant,3.7,61.1k,IT Services & Consulting | Hyderabad +231 othe...,6L
4,Capgemini,3.6,53k,IT Services & Consulting | Bengaluru +180 othe...,4.9L
...,...,...,...,...,...
115,Shapoorji Pallonji Group,4.1,5.7k,Engineering & Construction | Mumbai +189 other...,15.6k
116,UST,3.7,5.7k,IT Services & Consulting | Bengaluru +52 other...,40.1k
117,Apollo Hospitals,4.0,5.6k,Healthcare | Chennai +225 other locations,16.8k
118,Bosch Global Software Technologies,3.7,5.6k,IT Services & Consulting | Bengaluru +47 other...,41.1k
119,Mahindra Finance,3.9,5.6k,NBFC | Mumbai +736 other locations,12.3k

In [47]:
final.to_csv('120_companies_data.csv')